import { AncientTraitInterface } from "./ancient-trait.interface";
import { AbilityInterface } from "./ability.interface";
import { AttackInterface } from "./attack.interface";
import { WeaknessInterface } from "./weakness.interface";
import { ResistanceInterface } from "./resistance.interface";
import { SetInterface } from "./set.interface";
import { LegalityInterface } from "./legality.interface";
import { CardImageInterface } from "./image";
import { ITCGPlayerInterface } from "./tcgplayer.interface";
import { CardMarketInterface } from "./card-market.interface";

export interface CardInterface {
  id: string;
  name: string;
  supertype: string;
  subtypes: string[];
  hp?: string;
  types?: string[];
  evolvesFrom?: string;
  evolvesTo?: string[];
  rules?: string[];
  ancientTrait?: AncientTraitInterface;
  abilities?: AbilityInterface[];
  attacks?: AttackInterface[];
  weaknesses?: WeaknessInterface[];
  resistances?: ResistanceInterface[];
  retreatCost?: string[];
  convertedRetreatCost?: number;
  set: SetInterface;
  number: string;
  artist?: string;
  rarity: string;
  flavorText?: string;
  nationalPokedexNumbers?: number[];
  legalities: LegalityInterface;
  regulationMark?: string;
  images: CardImageInterface;
  tcgplayer?: ITCGPlayerInterface;
  cardmarket?: CardMarketInterface;
}